"""
main.py

Phase 17: Backend API.

A FastAPI backend wrapping the RAG pipeline built in earlier phases. FastAPI
was chosen (as the phase brief suggested) because it gives automatic request
validation (via the Pydantic schemas in schemas.py), automatic interactive
API documentation at /docs, and async support — all with minimal boilerplate
compared to Flask, and without Django's much heavier full-framework footprint
that this project doesn't need.

RATE LIMITING — why it's "appropriate" here, not just boilerplate:
This project hit REAL rate limits from the Gemini API repeatedly during
development (see rag_pipeline.py's generate_with_retry, added after actually
running into 429 errors during evaluation). The backend sits in front of
that same limited resource, so without our own rate limiting, a handful of
enthusiastic API users could exhaust the free-tier quota for everyone in
minutes. We rate-limit the expensive endpoints (/ask, /compare — anything
that calls Gemini) more strictly than the cheap, local-lookup endpoints
(/health, /trials, /papers).

Run locally:
    uvicorn src.api.main:app --reload

Then visit http://127.0.0.1:8000/docs for interactive API documentation
(auto-generated by FastAPI from the Pydantic schemas and docstrings below).
"""

import logging
import os
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from src.config import PROJECT_ROOT, GEMINI_MODEL_NAME
from src.rag_pipeline import answer_question, get_chunks_for_explicit_ids, PROMPT_VERSION
from src.hybrid_retrieval import hybrid_search_raw
from src.citations import build_citation_record
from src.database import init_db, log_query_and_answer, get_source as get_db_source
from src.api.schemas import (
    SearchRequest,
    AskRequest,
    CompareRequest,
    SearchResponse,
    AskResponse,
    CompareResponse,
    ChunkResult,
    CitationInfo,
    VerificationSummary,
    SourceDetail,
    HealthResponse,
)

# ---------- Configuration via environment variables ----------
API_HOST = os.getenv("API_HOST", "0.0.0.0")
API_PORT = int(os.getenv("API_PORT", "8000"))
CORS_ORIGINS = os.getenv("CORS_ORIGINS", "*").split(",")
RATE_LIMIT_ASK = os.getenv("RATE_LIMIT_ASK", "10/minute")
RATE_LIMIT_COMPARE = os.getenv("RATE_LIMIT_COMPARE", "5/minute")
RATE_LIMIT_SEARCH = os.getenv("RATE_LIMIT_SEARCH", "30/minute")
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

# ---------- Logging ----------
logging.basicConfig(
    level=LOG_LEVEL,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("clinical_rag_api")

# ---------- Rate limiter ----------
limiter = Limiter(key_func=get_remote_address)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup/shutdown logic — logs when the API comes online and checks basic readiness."""
    logger.info("Clinical RAG API starting up...")
    init_db()
    logger.info("Database schema ready.")
    corpus_path = PROJECT_ROOT / "data" / "processed" / "chunks.jsonl"
    vector_db_path = PROJECT_ROOT / "data" / "vector_db"
    if not corpus_path.exists():
        logger.warning("Corpus file not found at %s — /search and /ask will fail until it exists", corpus_path)
    if not vector_db_path.exists():
        logger.warning("Vector DB not found at %s — run build_vector_db.py first", vector_db_path)
    yield
    logger.info("Clinical RAG API shutting down...")


app = FastAPI(
    title="Clinical Trial & Medical Literature RAG API",
    description=(
        "A citation-grounded question-answering API over clinical trials and "
        "medical literature. This is NOT a diagnostic tool and does not provide "
        "personalized medical advice — see the /ask endpoint's refusal behavior "
        "for details."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.middleware("http")
async def log_requests(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    duration_ms = (time.time() - start_time) * 1000
    logger.info(
        "%s %s -> %s (%.1fms)",
        request.method,
        request.url.path,
        response.status_code,
        duration_ms,
    )
    return response


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """
    Catches anything not already handled as an HTTPException, logs the full
    error server-side (for debugging), and returns a generic, safe message
    to the client — never leaking internal stack traces or file paths.
    """
    logger.exception("Unhandled error on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"error": "internal_server_error", "detail": "An unexpected error occurred. Please try again."},
    )


def load_all_chunks() -> list[dict]:
    """Load the full chunk corpus from disk."""
    import json

    chunks_path = PROJECT_ROOT / "data" / "processed" / "chunks.jsonl"
    chunks = []
    with open(chunks_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                chunks.append(json.loads(line))
    return chunks


def chunks_to_citation_infos(evidence_chunks: list[dict]) -> list[CitationInfo]:
    infos = []
    for chunk in evidence_chunks:
        record = build_citation_record(chunk)
        infos.append(
            CitationInfo(
                source_type=record["source_type"],
                nct_id=record["nct_id"],
                pmid=record["pmid"],
                pmcid=record["pmcid"],
                doi=record["doi"],
                title=record["title"],
                section=record["section"],
            )
        )
    return infos


def verification_report_to_summary(report):
    if not report:
        return None
    return VerificationSummary(
        total_citations=report.get("total_citations", 0),
        verified_count=report.get("verified_count", 0),
        fabricated_count=report.get("fabricated_count", 0),
        numeric_mismatch_count=report.get("numeric_mismatch_count", 0),
        passed=report.get("passed", False),
    )


FRONTEND_PATH = PROJECT_ROOT / "frontend" / "index.html"


@app.get("/", include_in_schema=False)
async def serve_frontend():
    """
    Serves the frontend directly from the backend — merging what used to
    be two separate things (backend on one port via uvicorn, frontend on
    another via Live Server) into a single server, single command, single
    URL. This also eliminates any real CORS concern for normal usage: the
    frontend now IS the same origin as the API, not a separate one.
    """
    if not FRONTEND_PATH.exists():
        raise HTTPException(status_code=404, detail="Frontend file not found. Expected at frontend/index.html")
    return FileResponse(FRONTEND_PATH)


@app.get("/health", response_model=HealthResponse, tags=["system"])
async def health_check():
    """
    Basic liveness/readiness check. Confirms the API process is running and
    whether the corpus and vector database files exist on disk. No rate
    limit — this endpoint is cheap and monitoring tools may call it frequently.
    """
    corpus_path = PROJECT_ROOT / "data" / "processed" / "chunks.jsonl"
    vector_db_path = PROJECT_ROOT / "data" / "vector_db"
    return HealthResponse(
        status="ok",
        corpus_loaded=corpus_path.exists(),
        vector_db_ready=vector_db_path.exists(),
    )


@app.get("/sources/{source_id}", response_model=SourceDetail, tags=["sources"])
async def get_source(source_id: str):
    """
    Fetch full details for any source by its exact ID — an NCT number
    (e.g. NCT01057251) or a bare PubMed ID (e.g. 42572726). Returns 404 if
    the ID doesn't exist in the corpus.

    PERFORMANCE FIX (Phase 18): this now checks the indexed `sources` table
    FIRST — a fast, indexed database lookup — before touching the full
    chunk corpus at all. Previously, EVERY request (including ones for IDs
    that don't exist) scanned the entire chunks.jsonl file into memory just
    to determine "not found." Now, a nonexistent ID gets an instant 404 from
    the database with zero file I/O; only IDs confirmed to exist go on to
    fetch their full section text from chunks.jsonl (since we deliberately
    don't duplicate full text into SQL — see database.py's design notes).
    """
    normalized_id = source_id.upper() if source_id.upper().startswith("NCT") else source_id

    db_row = get_db_source(normalized_id)
    if not db_row:
        logger.info("Source not found (fast index lookup): %s", source_id)
        raise HTTPException(status_code=404, detail=f"No source found with ID '{source_id}'")

    chunks = get_chunks_for_explicit_ids([normalized_id])
    sections = [{"section_name": c["section_name"], "text": c["text"]} for c in chunks]
    return SourceDetail(
        source_id=db_row["source_id"],
        source_type=db_row["source_type"],
        title=db_row["title"],
        sections=sections,
        metadata=chunks[0].get("metadata", {}) if chunks else {},
    )


@app.get("/trials/{nct_id}", response_model=SourceDetail, tags=["sources"])
async def get_trial(nct_id: str):
    """Fetch a specific clinical trial by its NCT ID (e.g. NCT01057251). Returns 404 if not found."""
    if not nct_id.upper().startswith("NCT"):
        raise HTTPException(status_code=400, detail="nct_id must start with 'NCT' (e.g. NCT01057251)")
    return await get_source(nct_id.upper())


@app.get("/papers/{pmid}", response_model=SourceDetail, tags=["sources"])
async def get_paper(pmid: str):
    """Fetch a specific PubMed paper by its bare numeric PMID (e.g. 42572726). Returns 404 if not found."""
    if not pmid.isdigit():
        raise HTTPException(status_code=400, detail="pmid must be a numeric string (e.g. 42572726)")
    return await get_source(pmid)


@app.post("/search", response_model=SearchResponse, tags=["retrieval"])
@limiter.limit(RATE_LIMIT_SEARCH)
async def search(request: Request, body: SearchRequest):
    """
    Run hybrid (semantic + keyword) search over the corpus and return the
    top matching chunks — without generating an LLM answer. Useful for
    inspecting retrieval quality directly, or building a custom UI.
    """
    try:
        result = hybrid_search_raw(body.query, condition_filter=body.condition, top_k=body.top_k)
    except Exception as e:
        logger.exception("Search failed for query: %s", body.query)
        raise HTTPException(status_code=500, detail="Search failed due to an internal error.") from e

    results = [
        ChunkResult(
            chunk_id=chunk["chunk_id"],
            source_type=chunk["source_type"],
            source_id=chunk["source_id"],
            title=chunk["title"],
            section_name=chunk["section_name"],
            text=chunk["text"],
        )
        for chunk in result["chunks"]
    ]

    return SearchResponse(
        query=body.query,
        condition_filter=body.condition,
        results=results,
        low_confidence=result["low_confidence"],
    )


@app.post("/ask", response_model=AskResponse, tags=["generation"])
@limiter.limit(RATE_LIMIT_ASK)
async def ask(request: Request, body: AskRequest):
    """
    Ask a question and get a citation-grounded, verified answer. Runs the
    full pipeline (preprocessing, retrieval, reranking, LLM generation,
    citation verification) and returns a structured answer with citations.

    Rate-limited more strictly than /search since each call makes a real
    Gemini API request (or two, if verification triggers a correction retry).
    """
    try:
        result = answer_question(body.question, condition_filter=body.condition, verbose=False)
    except Exception as e:
        logger.exception("Ask failed for question: %s", body.question)
        raise HTTPException(status_code=500, detail="Failed to generate an answer due to an internal error.") from e

    log_query_and_answer(
        question=body.question,
        condition_filter=body.condition,
        low_confidence=result["low_confidence"],
        answer_text=result["answer_text"],
        refused=result["refused"],
        verification_report=result["verification_report"],
        llm_model=GEMINI_MODEL_NAME,
        prompt_version=PROMPT_VERSION,
    )

    return AskResponse(
        question=body.question,
        answer=result["answer_text"],
        refused=result["refused"],
        low_confidence=result["low_confidence"],
        citations=chunks_to_citation_infos(result["evidence_chunks"]),
        verification=verification_report_to_summary(result["verification_report"]),
    )


@app.post("/compare", response_model=CompareResponse, tags=["generation"])
@limiter.limit(RATE_LIMIT_COMPARE)
async def compare(request: Request, body: CompareRequest):
    """
    Compare 2-5 specific trials/papers by ID. Builds a comparison question
    naming all requested IDs and reuses the /ask pipeline — including the
    explicit-ID pinning fix from evaluation, which guarantees each named
    source actually appears in the evidence used, rather than leaving it to
    chance via similarity search.
    """
    aspect_phrase = body.aspect or "key characteristics (phase, design, eligibility, and outcomes)"
    question = f"Compare the {aspect_phrase} of the following trials/papers: {', '.join(body.source_ids)}."

    try:
        result = answer_question(question, verbose=False)
    except Exception as e:
        logger.exception("Compare failed for sources: %s", body.source_ids)
        raise HTTPException(status_code=500, detail="Failed to generate a comparison due to an internal error.") from e

    return CompareResponse(
        source_ids=body.source_ids,
        aspect=body.aspect,
        comparison=result["answer_text"],
        citations=chunks_to_citation_infos(result["evidence_chunks"]),
        verification=verification_report_to_summary(result["verification_report"]),
    )
